name: Release

on:
  push:
    branches: [ "master" ]
    tags: 
      - "*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          
      - name: Install node modules
        run: npm install

      - name: Get tag    
        id: tag
        uses: dawidd6/action-get-tag@v1.1.0

      - name: Build Project
        run: npm run release -- --configLatest=${{steps.tag.outputs.tag}}
        
      - name: Get System ID
        id: systemID
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'system.json'
          prop_path: 'id'

      - name: Create ZIP
        run: |
          cd build
          zip -r ../${{steps.systemID.outputs.prop}}.zip *
          
      - name: Get mininum
        id: minimum
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'system.json'
          prop_path: 'compatibility.minimum'

      - name: Get verified
        id: verified
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'system.json'
          prop_path: 'compatibility.verified'

      - name: Get maximum
        id: maximum
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'system.json'
          prop_path: 'compatibility.maximum'

      - name: Foundry Release API
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://foundryvtt.com/_api/packages/release_version'
          method: 'POST'
          preventFailureOnNoResponse: true
          customHeaders: '{"Content-Type": "application/json", "Authorization" : "${{ secrets.FOUNDRY_KEY }}"}'
          data: '{"dry_run": false, "id" : "${{steps.systemID.outputs.prop}}", "release": {"version" :  "${{steps.tag.outputs.tag}}", "manifest": "https://github.com/${{github.repository}}/releases/download/${{steps.tag.outputs.tag}}/system.json", "notes" : "https://github.com/${{github.repository}}/releases/tag/${{steps.tag.outputs.tag}}", "compatibility" : {"minimum": "${{steps.minimum.outputs.prop}}", "verified": "${{steps.verified.outputs.prop}}", "maximum": "${{steps.maximum.outputs.prop}}"} } }'
          
      # - name: Generate Changelog
      #   id: changelog
      #   uses: mikepenz/release-changelog-builder-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }}
          
      - name: Create Release
        uses: ncipollo/release-action@v1.9.0
        with:
          token: ${{ secrets.PAT }}
          artifacts: "./build/system.json, ./${{steps.systemID.outputs.prop}}.zip"
          draft : true
          generateReleaseNotes : true
